cleanup

diff --git a/rock b/rock
--- a/rock
+++ b/rock
@@ -1,11 +1,24 @@
 #!/bin/bash
-
-# options:
-#  rock [-t zxn|gcc] [--target=zxn|gcc] [--debug] filename
+set -e
 
 ROCK_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 CLIB=sdcc_iy    # z88dk main library
 RT="${ROCK_ROOT}/src"
+AUTO_CAST=""
+sourcefile=""
+target="gcc"
+nex_file=""
+
+DEBUG=0
+RUN=0
+
+usage() {
+  echo "usage: rock [run] [-t zxn|gcc] [--target=zxn|gcc] [--debug] filename"
+}
+
+if [ $# -eq 0 ]; then 
+  usage; exit 1
+fi
 
 # ---------------------------------------------------------------------------
 # Rock RTL manifest
@@ -55,6 +68,7 @@ RTL_HOST_SRCS="\
 RTL_ZXN_ASM="\
   $RT/lib/zxn/keyboard.asm"
 
+
 transpile() {
   local target="$1" exe_abs="$2" source_abs="$3" auto_cast="$4"
   local extra=""
@@ -64,16 +78,15 @@ transpile() {
 
 build() {
   local target="$1" exe_abs="$2" sourcefile="$3"
-
-  echo "compile $sourcefile -> $exe_abs"
-
   local LIB_SRCS="${RTL_CORE_SRCS} ${RTL_C_SRCS}"
+  echo "compile $sourcefile -> $exe_abs"
 
   if [ "$target" = "gcc" ]; then
     gcc -Wall -Wno-unused-variable \
       -I "${RT}/lib" -I "${RT}/ext/lib" \
       -o "${exe_abs}" "${exe_abs}.c" ${LIB_SRCS} ${RTL_HOST_SRCS} -lm
   else
+    nex_file="${exe_abs%%.*}.nex"
     zcc +zxn -vn -subtype=nex -startup=1 -clib=$CLIB -create-app \
       -pragma-include:"${RT}/lib/zxn/zpragma_zxn.inc" \
       -I"${RT}/lib" \
@@ -86,22 +99,22 @@ build() {
       echo "created $exe_abs"
     else
       rm -f "${exe_abs}"
-      local nex_file="${exe_abs%%.*}.nex"
       echo "created $nex_file"
     fi
+  else
+    echo "build failed"
+    exit 1
   fi
 }
 
 
-set -e
-DEBUG=0
-AUTO_CAST=""
-
-sourcefile=""
-target="gcc"
-
 while [ $# -gt 0 ]; do
   case "$1" in
+    run)
+      RUN=1
+      shift 1
+      ;;
+
     -t)
       target="${2}"
       shift 2
@@ -131,6 +144,11 @@ while [ $# -gt 0 ]; do
   esac
 done
 
+
+if [ "$sourcefile" = "" ]; then
+  usage; exit 1
+fi
+
 [ $DEBUG -eq 1 ] && echo "target=$target exe=$exe_abs auto_cast=$AUTO_CAST"
 transpile "$target" "$exe_abs" "$source_abs" "$AUTO_CAST"
 build "$target" "$exe_abs" "$sourcefile"
@@ -140,3 +158,14 @@ if [ $DEBUG -eq 0 ]; then
 else
   clang-format -i "${exe_abs}.c"
 fi
+
+if [ $RUN -ne 0 ]; then
+  if [ -f "$exe_abs" ]; then
+    if [ "$target" = "zxn" ]; then
+      zx $nex_file
+    else
+      $exe_abs
+    fi
+  fi
+fi
+
